// Badge catalog: 20 badges with deterministic, queryable conditions
// This is the single source of truth for badge definitions

export type BadgeShape = 'circle' | 'hex' | 'shield' | 'ribbon' | 'badge' | 'medal';
export type BadgeCategory = 'activity' | 'community' | 'growth' | 'consistency';
export type BadgeOperator = 'gte' | 'eq' | 'lte';

export interface BadgeDefinition {
  key: string;
  title: string;
  description: string;
  how_to_get: string;
  metric: string;
  operator: BadgeOperator;
  threshold: number;
  icon: string; // lucide-react icon name
  color_start: string; // tailwind color class
  color_end: string; // tailwind color class
  shape: BadgeShape;
  category: BadgeCategory;
}

export const BADGE_CATALOG: BadgeDefinition[] = [
  {
    key: 'new_voice',
    title: 'New Voice',
    description: 'You have started sharing your thoughts with the community.',
    how_to_get: 'Publish at least 3 posts and write at least 5 comments.',
    metric: 'composite_posts_comments_3_5',
    operator: 'gte',
    threshold: 1,
    icon: 'MessageSquarePlus',
    color_start: 'indigo-500',
    color_end: 'purple-500',
    shape: 'circle',
    category: 'activity',
  },
  {
    key: 'active_member',
    title: 'Active Member',
    description: 'Consistent early participation.',
    how_to_get: 'Publish at least 5 posts and write at least 10 comments.',
    metric: 'composite_posts_comments_5_10',
    operator: 'gte',
    threshold: 1,
    icon: 'UserCheck',
    color_start: 'sky-500',
    color_end: 'emerald-500',
    shape: 'shield',
    category: 'activity',
  },
  {
    key: 'contributor',
    title: 'Contributor',
    description: 'A regular contributor to discussions.',
    how_to_get: 'Publish at least 20 posts and write at least 50 comments.',
    metric: 'composite_posts_comments_20_50',
    operator: 'gte',
    threshold: 1,
    icon: 'Send',
    color_start: 'violet-500',
    color_end: 'fuchsia-500',
    shape: 'hex',
    category: 'activity',
  },
  {
    key: 'talkative',
    title: 'Talkative',
    description: 'You keep the conversations flowing.',
    how_to_get: 'Write at least 100 comments.',
    metric: 'total_comments',
    operator: 'gte',
    threshold: 100,
    icon: 'MessageCircle',
    color_start: 'cyan-500',
    color_end: 'blue-500',
    shape: 'circle',
    category: 'activity',
  },
  {
    key: 'supporter',
    title: 'Supporter',
    description: 'You encourage others with reactions.',
    how_to_get: 'Give at least 50 likes to other users.',
    metric: 'likes_given',
    operator: 'gte',
    threshold: 50,
    icon: 'ThumbsUp',
    color_start: 'emerald-500',
    color_end: 'teal-500',
    shape: 'ribbon',
    category: 'community',
  },
  {
    key: 'daily_spark',
    title: 'Daily Spark',
    description: 'A week of steady activity.',
    how_to_get: 'Be active 7 days in a row.',
    metric: 'consecutive_active_days',
    operator: 'gte',
    threshold: 7,
    icon: 'Sparkles',
    color_start: 'amber-500',
    color_end: 'orange-500',
    shape: 'circle',
    category: 'consistency',
  },
  {
    key: 'consistent_creator',
    title: 'Consistent Creator',
    description: 'Creating regularly over time.',
    how_to_get: 'Publish at least 14 posts in the last 30 days.',
    metric: 'total_posts_last_30d',
    operator: 'gte',
    threshold: 14,
    icon: 'CalendarCheck',
    color_start: 'rose-500',
    color_end: 'pink-500',
    shape: 'shield',
    category: 'consistency',
  },
  {
    key: 'momentum_builder',
    title: 'Momentum Builder',
    description: 'Week after week of engagement.',
    how_to_get: 'Have activity at least 1 day per week for 8 consecutive weeks.',
    metric: 'weekly_active_streak',
    operator: 'gte',
    threshold: 8,
    icon: 'Timer',
    color_start: 'slate-500',
    color_end: 'zinc-500',
    shape: 'hex',
    category: 'consistency',
  },
  {
    key: 'feedback_hero',
    title: 'Feedback Hero',
    description: 'The community reacts to your posts.',
    how_to_get: 'Collect at least 50 reactions on your posts.',
    metric: 'post_reactions_received',
    operator: 'gte',
    threshold: 50,
    icon: 'Heart',
    color_start: 'red-500',
    color_end: 'rose-500',
    shape: 'circle',
    category: 'growth',
  },
  {
    key: 'comment_magnet',
    title: 'Comment Magnet',
    description: 'Diverse voices join your threads.',
    how_to_get: 'Get comments from at least 10 distinct users on your posts.',
    metric: 'distinct_commenters',
    operator: 'gte',
    threshold: 10,
    icon: 'Users',
    color_start: 'yellow-500',
    color_end: 'lime-500',
    shape: 'badge',
    category: 'growth',
  },
  {
    key: 'connector',
    title: 'Connector',
    description: 'You bring new people in.',
    how_to_get: 'Invite at least 3 users who register.',
    metric: 'invited_users_total',
    operator: 'gte',
    threshold: 3,
    icon: 'Link2',
    color_start: 'blue-500',
    color_end: 'indigo-500',
    shape: 'ribbon',
    category: 'community',
  },
  {
    key: 'growth_networker',
    title: 'Growth Networker',
    description: 'Your invites become active members.',
    how_to_get: 'Invite at least 10 users who make at least 1 post or comment.',
    metric: 'invited_users_with_activity',
    operator: 'gte',
    threshold: 10,
    icon: 'Network',
    color_start: 'emerald-500',
    color_end: 'green-500',
    shape: 'shield',
    category: 'community',
  },
  {
    key: 'community_helper',
    title: 'Community Helper',
    description: 'You nurture others\' posts.',
    how_to_get: 'Leave at least 20 comments on other users\' posts.',
    metric: 'comments_on_others_posts',
    operator: 'gte',
    threshold: 20,
    icon: 'HelpingHand',
    color_start: 'teal-500',
    color_end: 'cyan-500',
    shape: 'hex',
    category: 'community',
  },
  {
    key: 'collaboration_spirit',
    title: 'Collaboration Spirit',
    description: 'Deep participation in discussions.',
    how_to_get: 'Participate in at least 5 threads where you wrote 10 or more comments.',
    metric: 'threads_with_10_comments',
    operator: 'gte',
    threshold: 5,
    icon: 'MessagesSquare',
    color_start: 'purple-500',
    color_end: 'violet-500',
    shape: 'circle',
    category: 'community',
  },
  {
    key: 'badge_collector',
    title: 'Badge Collector',
    description: 'Collect achievements along the way.',
    how_to_get: 'Earn at least 10 other badges.',
    metric: 'earned_badges_count',
    operator: 'gte',
    threshold: 10,
    icon: 'Award',
    color_start: 'amber-500',
    color_end: 'yellow-500',
    shape: 'medal',
    category: 'growth',
  },
  {
    key: 'mentor',
    title: 'Mentor',
    description: 'Your comments are marked helpful.',
    how_to_get: 'Receive likes on comments from at least 5 distinct users.',
    metric: 'comment_likes_from_distinct_users',
    operator: 'gte',
    threshold: 5,
    icon: 'BookOpenCheck',
    color_start: 'stone-500',
    color_end: 'neutral-500',
    shape: 'shield',
    category: 'growth',
  },
  {
    key: 'recognized_voice',
    title: 'Recognized Voice',
    description: 'Your work resonates widely.',
    how_to_get: 'Receive at least 200 total likes.',
    metric: 'total_likes_received',
    operator: 'gte',
    threshold: 200,
    icon: 'Megaphone',
    color_start: 'fuchsia-500',
    color_end: 'rose-500',
    shape: 'hex',
    category: 'growth',
  },
  {
    key: 'post_achiever',
    title: 'Post Achiever',
    description: 'Consistent posting at scale.',
    how_to_get: 'Publish at least 50 posts.',
    metric: 'total_posts',
    operator: 'gte',
    threshold: 50,
    icon: 'FilePlus2',
    color_start: 'blue-500',
    color_end: 'cyan-500',
    shape: 'badge',
    category: 'activity',
  },
  {
    key: 'community_veteran',
    title: 'Community Veteran',
    description: 'Long term participation.',
    how_to_get: 'Be active on more than 100 days since registration.',
    metric: 'active_days',
    operator: 'gte',
    threshold: 100,
    icon: 'Hourglass',
    color_start: 'orange-500',
    color_end: 'amber-500',
    shape: 'shield',
    category: 'consistency',
  },
  {
    key: 'sw_master',
    title: 'SW Master',
    description: 'High Social Weight achieved.',
    how_to_get: 'Reach Social Weight of at least 500.',
    metric: 'social_weight',
    operator: 'gte',
    threshold: 500,
    icon: 'Scale',
    color_start: 'emerald-500',
    color_end: 'lime-500',
    shape: 'circle',
    category: 'growth',
  },
];

// Helper to find badge by key
export function getBadgeByKey(key: string): BadgeDefinition | undefined {
  return BADGE_CATALOG.find((badge) => badge.key === key);
}

// Helper to get badges by category
export function getBadgesByCategory(category: BadgeCategory): BadgeDefinition[] {
  return BADGE_CATALOG.filter((badge) => badge.category === category);
}

// Type for badge with earned status
export interface BadgeWithStatus extends BadgeDefinition {
  earned: boolean;
  awardedAt?: string;
  progress: number; // 0-1
  currentValue: number;
}
